// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "qroboteventctrl1.h"

/////////////////////////////////////////////////////////////////////////////
// CQroboteventctrl1

IMPLEMENT_DYNCREATE(CQroboteventctrl1, CWnd)

/////////////////////////////////////////////////////////////////////////////
// CQroboteventctrl1 properties

/////////////////////////////////////////////////////////////////////////////
// CQroboteventctrl1 operations
